# Generated by Django 4.2.10 on 2024-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="no_of_guests",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(null=True),
        ),
    ]
